[package]
name = "halloy"
version = "0.1.0"
authors = ["Casper Rogild Storm", "Cory Forsstrom"]
description = "Halloy is an open-source IRC client written in Rust, with the Iced GUI library. It aims to provide a simple and fast client for Mac, Windows, and Linux platforms."
documentation = "https://halloy.squidowl.org/"
license = "LICENSE"
edition = "2021"

[features]
default = []
debug = ["iced/debug"]
dev = ["debug", "data/dev"]

[dependencies]
data = { version = "0.1.0", path = "data" }
ipc = { version = "0.1.0", path = "ipc" }

notify-rust = "4"
chrono = { version = "0.4", features = ['serde'] }
fern = "0.6.1"
iced = { version = "0.13.0-dev", features = [
    "tokio",
    "lazy",
    "advanced",
    "image",
] }
log = "0.4.16"
once_cell = "1.18"
palette = "0.7.4"
thiserror = "1.0.30"
tokio = { version = "1.0", features = ["rt", "fs", "process"] }
unicode-segmentation = "1.6"
open = "5.0.1"
bytesize = "1.3.0"
timeago = "0.4.2"
futures = "0.3.30"
itertools = "0.13.0"
rodio = "0.19.0"

[dependencies.uuid]
version = "1.0"
features = ["v4"]

[dependencies.rfd]
version = "0.14.1"
default-features = false
features = ["xdg-portal", "tokio"]

[target.'cfg(windows)'.dependencies]
image = "0.24.6"

[build-dependencies]
embed-resource = "2.1.1"
windows_exe_info = "0.4"
cargo-edit = "0.12"

[workspace]
members = ["data", "ipc", "irc", "irc/proto"]

[patch.crates-io]
iced = { git = "https://github.com/iced-rs/iced", rev = "5443e4d8289873895587d856dbcf46f980bda6ab" }
iced_core = { git = "https://github.com/iced-rs/iced", rev = "5443e4d8289873895587d856dbcf46f980bda6ab" }
