[general]
background = "#f4ece6"
horizontal_rule = "#e9d9ce"
unread_indicator = "#ffa07a"
border = "#ddd0c8"

[text]
primary = "#685650"
secondary = "#a79891"
tertiary = "#a352c5"
success = "#74862d"
error = "#df525e"

[buffer]
background = "#f1e6de"
background_text_input = "#eee0d5"
background_title_bar = "#efe2d8"
timestamp = "#ae9d95"
action = "#74862d"
topic = "#AB8A79"
highlight = "#f4d6c7"
code = "#a352c5"
nickname = "#c4486c"
url = "#6360d6"
selection = "#e6c6c3"
border_selected = "#c7b9b1"

[buffer.server_messages]
default = "#c19317"

[buttons.primary]
background = "#f4ece6"
background_hover = "#f1e5dd"
background_selected = "#eadad0"
background_selected_hover = "#e6d5c9"

[buttons.secondary]
background = "#e9d5c8"
background_hover = "#dfc2ad"
background_selected = "#d9d1bb"
background_selected_hover = "#c9c5a7"
