[package]
name = "ipc"
authors = ["Casper Rogild Storm", "Cory Forsstrom"]
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["rt", "fs", "process"] }
futures = "0.3.28"
interprocess = { version = "1.2.1", features = ["tokio_support"] }
thiserror = "1.0.30"
url = "2.5.0"
rand = "0.8.4"
rand_chacha = "0.3.0"

[dependencies.data]
path = "../data"
